### Debug Get all users
GET http://localhost:8081/users

#####################################################################

### Admin Get all users
GET http://localhost:8081/admin/users
Authorization: Bearer <token>

#####################################################################

### Admin Get user by id
GET http://localhost:8081/users/9
Authorization: Bearer <token>

#####################################################################

### Get valid Session
GET http://localhost:8081/auth/session
Authorization: Bearer <token>

#####################################################################

### Create User
POST http://localhost:8081/users
Content-Type: application/json

{
  "userName": "yekotest",
  "userPin": "test",
  "userId": 999,
  "role": "SELECT user_pin FROM users",
  "hacked": true
}

#####################################################################

### login user
POST http://localhost:8081/auth/login
Content-Type: application/json

{
  "userName": "yeko45",
  "userPin": "45",
  "role": "asda",
  "hack": true
}

#####################################################################

### login admin
POST http://localhost:8081/auth/login
Content-Type: application/json

{
  "userName": "yekoAdmin",
  "userPin": "admin",
  "role": "asda",
  "hack": true
}

#####################################################################

### Update user role
PATCH http://localhost:8081/admin/users/9/role
Authorization: Bearer <token>
Content-Type: application/json

{
  "userName": "kk",
  "newUserPin": "123",
  "userId": 999,
  "userRole": "user",
  "hacked": true
}

#####################################################################

### Update pin
PATCH http://localhost:8081/users/13/pin
Authorization: Bearer <token>
Content-Type: application/json

{
  "userName": "yekoAdmin",
  "userPin": "abc",
  "newUserPin": "admin",
  "userId": 999,
  "role": "ADMIN",
  "hacked": true
}

#####################################################################

### Delete user
DELETE http://localhost:8081/users/14
Authorization: Bearer <token>
Content-Type: application/json

{
  "userName": "yekotest",
  "userPin": "test",
  "newUserPin": "jghj",
  "userId": 999,
  "role": "ADMIN",
  "hacked": true
}
