spring.application.name=login-api
spring.datasource.url=jdbc:postgresql://localhost:5432/login_app_db
spring.datasource.username=userName
spring.datasource.password=password
server.port=0000

jwt.secret=secret-key
jwt.duration-millis=1800000
